spring.application.name=tiffy
# Application port
server.port=8081
# MySQL Connection
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.110.133:3307/tiffy?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
# Running query console output
spring.jpa.properties.hibernate.show_sql=true
# Query Formatting
spring.jpa.properties.hibernate.format_sql=true
# Bind parameter output
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Live Reload
spring.devtools.livereload.enabled=true
# API Keys
api.recipe.key=bae867e89f8c4e05a317
api.map.key=1abf99a7eaabed5bf02b329ee8596ee0
# JWT Secret key
jwt.secret.key=LdqLV8d0ebKHnGek2HIOvmVtCaQHt914k7mTEZQYo33m2SUzvSVgWrBwzN2gnQ1rR0Joq90Lp9D7mFx0FLMQ1mwuV32ufB
# CORS Allowed Origin
cors.allowed.origin=http://192.168.0.125:8080
# MyBatis
mybatis.mapper-locations=classpath:/mappers/*.xml
mybatis.type-aliases-package=com.tiffy.entity
